/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef worker_CONSTANTS_H
#define worker_CONSTANTS_H

#include "worker_types.h"



class workerConstants {
 public:
  workerConstants();

};

extern const workerConstants g_worker_constants;



#endif
