/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vm_worker_CONSTANTS_H
#define vm_worker_CONSTANTS_H

#include "vm_worker_types.h"



class vm_workerConstants {
 public:
  vm_workerConstants();

};

extern const vm_workerConstants g_vm_worker_constants;



#endif
