/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vm_worker_constants.h"



const vm_workerConstants g_vm_worker_constants;

vm_workerConstants::vm_workerConstants() {
}



